### ISSUE TITLE
No working anymore? 

### ISSUE THREAD

**Issue by ofou** [PhoenixDD/Cheapest-Flights-bot#3]
I tried to run it but it raised an error. ` TimeoutException()` I wonder if it's currently working or it's just me who's experiencing this error?

**Comment by PhoenixDD** [comment]
Yes, It was made for an older version of google flights, since it's a bot based on the characteristics of elements on the page using selenium, any changes in the page would require to update the bot as well. It is mostly due to this that you must be getting the TimeoutException. Feel free to pull, make changes and merge if you want to.
